'use client';
import {createContext,useContext,useState,useEffect,type ReactNode} from 'react';
import {settingsDefaults,destinations} from '@/lib/data';
import {DropdownMenu,DropdownMenuContent,DropdownMenuItem,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';
import {Sheet,SheetContent,SheetTitle,SheetTrigger} from '@/components/ui/sheet';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {DirectionProvider} from '@/components/ui/direction';
import {Globe,ChevronDown,Menu,ArrowRight,ExternalLink,Phone,Mail,MapPin,Loader2} from 'lucide-react';
const Ctx=createContext<any>(null);
export function Provider({children,initial={}}:{children:ReactNode,initial?:any}){const [lang,setLang]=useState(initial.lang||'en'),[settings,setSettings]=useState(initial.settings||settingsDefaults),[ports,setPorts]=useState(initial.ports||destinations),[user,setUser]=useState<any>(null),[articles,setArticles]=useState(initial.articles||[]);const ar=lang==='ar';const t=(en:string,arabic:string)=>ar?arabic:en;async function refresh(){try{const d=await api('bootstrap');setUser(d.user);setSettings(d.settings);setPorts(d.ports);setArticles(d.articles);return d.user}catch{return null}}useEffect(()=>{refresh()},[]);function switchLang(){const next=ar?'en':'ar';setLang(next);document.documentElement.lang=next;document.documentElement.dir=next==='ar'?'rtl':'ltr';document.cookie=`ccm_lang=${next}; path=/; max-age=31536000; SameSite=Lax`;}return <Ctx.Provider value={{lang,ar,t,switchLang,settings,setSettings,ports,user,setUser,refresh,articles}}><DirectionProvider dir={ar?'rtl':'ltr'}>{children}</DirectionProvider></Ctx.Provider>}
export const useSite=()=>useContext(Ctx);
export async function api(path:string,data?:any):Promise<any>{const form=data instanceof FormData;const r=await fetch('/api/'+path,{method:data===undefined?'GET':'POST',headers:data===undefined||form?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:form?data:JSON.stringify(data)});const d:any=await r.json();if(!r.ok){const e:any=new Error(d.error||'Please try again.');e.code=d.code;e.status=r.status;throw e}return d}
export function Logo({admin=false}:{admin?:boolean}){const {settings}=useSite();const src=admin?settings.adminLogo:settings.logo;return <a href="/" className="brand" aria-label="CCM home"><img src={src||'/assets/ccm-logo.png'} alt="CCM Commander Cargo Maritime"/></a>}
export function Header(){const {t,switchLang,ar,settings,user}=useSite();return <><div className="topline"><div className="wrap"><span>{t('Sokhna Port, Egypt. Your gateway to global trade.','ميناء السخنة، مصر. بوابتك للتجارة العالمية.')}</span><a className="top-email" href={'mailto:'+settings.email}>{settings.email}</a></div></div><header className="site-header"><div className="wrap header-row"><Logo/><nav className="nav" aria-label={t('Main navigation','القائمة الرئيسية')}>{settings.navigation.map((g:any)=><DropdownMenu key={g.label}><DropdownMenuTrigger className="nav-link">{ar?g.ar||g.label:g.label}<ChevronDown size={13}/></DropdownMenuTrigger><DropdownMenuContent className="nav-drop" align="start">{g.items.map((i:any)=><DropdownMenuItem key={i.href} asChild><a href={i.href}>{ar?i.ar||i.label:i.label}</a></DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>)}</nav><div className="head-actions"><button className="lang-btn" onClick={switchLang} aria-label={t('Switch to Arabic','Switch to English')}><Globe size={16}/>{ar?'EN':'العربية'}</button><a href={user?(user.role==='customer'?'/dashboard':'/admin'):'/login'} className="btn secondary small">{user?t('My account','حسابي'):t('Sign in','تسجيل الدخول')}<ArrowRight size={15}/></a><Sheet><SheetTrigger className="mobile-menu" aria-label={t('Open menu','افتح القائمة')}><Menu size={23}/></SheetTrigger><SheetContent><SheetTitle>CCM</SheetTitle><nav className="mobile-nav-list">{settings.navigation.flatMap((g:any)=>g.items).map((i:any)=><a key={i.href} href={i.href}>{ar?i.ar||i.label:i.label}</a>)}<a href={user?'/dashboard':'/login'}>{t('My account','حسابي')}</a></nav></SheetContent></Sheet></div></div></header></>}
export function Footer(){const{t,ar,settings:s}=useSite();return <footer className="footer"><div className="wrap"><div className="footer-grid"><div><Logo/><p style={{maxWidth:280}}>{ar?s.footerAr:s.footer}</p>{s.linkedin&&<a href={s.linkedin} target="_blank" rel="noreferrer" style={{display:'inline-flex',gap:8,marginTop:14}}><ExternalLink size={17}/> LinkedIn</a>}{[['facebook','Facebook'],['instagram','Instagram']].map(([k,n])=>s[k]&&<a key={k} href={s[k]} target="_blank" rel="noreferrer">{n}</a>)}{s.whatsapp&&<a href={'https://wa.me/'+s.whatsapp.replace(/\D/g,'')}>WhatsApp</a>}</div><div><h3>{t('Company','الشركة')}</h3><a href="/about">{t('About CCM','عن CCM')}</a><a href="/global-reach">{t('Global reach','شبكتنا العالمية')}</a><a href="/contact">{t('Contact us','تواصل معنا')}</a><a href="/guides">{t('Shipping guides & FAQs','دليل الشحن والأسئلة الشائعة')}</a></div><div><h3>{t('Solutions','حلولنا')}</h3><a href="/fcl-shipping-egypt">{t('FCL shipping','شحن الحاويات الكاملة')}</a><a href="/lcl-shipping-egypt">{t('LCL shipping','الشحن الجزئي')}</a><a href="/inland-transportation">{t('Inland transportation','النقل البري')}</a><a href="/track">{t('Track a shipment','تتبع شحنة')}</a></div><div><h3>{t('Let’s talk shipping','لنتحدث عن شحنتك')}</h3><a href={'tel:'+s.phone.replace(/\s/g,'')}><Phone size={14} style={{display:'inline',marginInlineEnd:8}}/><bdi>{s.phone}</bdi></a><a href={'mailto:'+s.email}><Mail size={14} style={{display:'inline',marginInlineEnd:8}}/>{s.email}</a><p><MapPin size={14} style={{display:'inline',marginInlineEnd:8}}/>{ar?s.addressAr:s.address}</p></div></div><div className="footer-base"><span>© {new Date().getFullYear()} CCM Shipping Agency. {t('All rights reserved.','جميع الحقوق محفوظة.')}</span><span><a href="/privacy" style={{display:'inline',marginInlineEnd:20}}>{t('Privacy & terms','الخصوصية والشروط')}</a><a href="/admin/login" style={{display:'inline'}}>{t('CCM team','فريق CCM')}</a></span></div></div></footer>}
export function Field({label,name,type='text',required=false,defaultValue,value,onChange,placeholder,children,...rest}:any){return <label className="block"><span className="form-label">{label}{required?' *':''}</span>{children||<input className="text-input" name={name} type={type} required={required} defaultValue={defaultValue} value={value} onChange={onChange} placeholder={placeholder} {...rest}/>}</label>}
export function Choice({value,onChange,items,placeholder,id}:any){return <Select value={value} onValueChange={onChange}><SelectTrigger id={id} className="control" style={{width:'100%',height:49}}><SelectValue placeholder={placeholder}/></SelectTrigger><SelectContent>{items.map((i:any)=><SelectItem key={i.value??i} value={String(i.value??i)}>{i.label??i}</SelectItem>)}</SelectContent></Select>}
export function RadioChoices({value,onChange,items,label}:any){return <RadioGroup aria-label={label} value={value} onValueChange={onChange} className="step-radio">{items.map((i:any)=><label className="radio-option" key={i.value??i}><RadioGroupItem value={i.value??i}/>{i.label??i}</label>)}</RadioGroup>}
export function Notice({error,success}:{error?:string,success?:string}){const{t}=useSite();return <>{error&&<p className="error" role="alert">{t(error,'تعذر إتمام الطلب. '+error)}</p>}{success&&<p className="success" role="status">{success}</p>}</>}
export function Submit({busy,children,...rest}:any){return <button className="btn" disabled={busy} type="submit" {...rest}>{busy?<Loader2 size={18} className="animate-spin"/>:null}{children}</button>}
export function Empty({icon:Icon=MapPin,title,text,children}:any){return <div className="empty-state"><Icon size={33}/><h3>{title}</h3><p style={{fontSize:14}}>{text}</p>{children}</div>}
export function Status({value}:any){const{t}=useSite();const labels:any={unverified:['Not verified','غير موثقة'],pending:['Verification pending','بانتظار المراجعة'],verified:['Verified','موثقة'],rejected:['Needs changes','تحتاج إلى تعديل'],requested:['Requested','طلب جديد'],confirmed:['Confirmed','مؤكد'],declined:['Declined','مرفوض'],cancelled:['Cancelled','ملغي'],new:['New','جديد'],contacted:['Contacted','تم التواصل'],closed:['Closed','مغلق']};return <span className={'status '+value}>{labels[value]?t(...labels[value]):value}</span>}
