export const ORIGIN='Sokhna Port, Egypt';
export const steps=['Booking Confirmed','Container Released','Loaded on Vessel','Vessel Departed','In Transit','Arrived at Destination','Discharged'];
export const stepsAr=['تم تأكيد الحجز','تم تسليم الحاوية','تم التحميل على السفينة','غادرت السفينة','في الطريق','وصلت إلى الوجهة','تم التفريغ'];
export const containers=["20' Dry","40' Dry","40' High Cube"];
export const destinations=[
['jeddah','Jeddah','جدة','Saudi Arabia','Red Sea & Gulf'],['aqaba','Aqaba','العقبة','Jordan','Red Sea & Gulf'],['sohar','Sohar','صحار','Oman','Red Sea & Gulf'],['jebel-ali','Jebel Ali','جبل علي','UAE','Red Sea & Gulf'],['khorfakkan','Khorfakkan','خورفكان','UAE','Red Sea & Gulf'],['bandar-abbas','Bandar Abbas','بندر عباس','Iran','Red Sea & Gulf'],
['nhava-sheva','Nhava Sheva','نهافا شيفا','India','Indian Subcontinent'],['mundra','Mundra','موندرا','India','Indian Subcontinent'],['tuticorin','Tuticorin','توتيكورين','India','Indian Subcontinent'],['chennai','Chennai','تشيناي','India','Indian Subcontinent'],['cochin','Cochin','كوتشين','India','Indian Subcontinent'],['kolkata','Kolkata','كولكاتا','India','Indian Subcontinent'],['vizag','Vizag','فيزاج','India','Indian Subcontinent'],['karachi','Karachi','كراتشي','Pakistan','Indian Subcontinent'],['other-india','Other Indian ports upon request','موانئ هندية أخرى عند الطلب','India','Indian Subcontinent'],
['port-klang','Port Klang','بورت كلانج','Malaysia','Far East / Southeast Asia'],['laem-chabang','Laem Chabang','لايم تشابانج','Thailand','Far East / Southeast Asia'],['penang','Penang','بينانج','Malaysia','Far East / Southeast Asia'],['jakarta','Jakarta','جاكرتا','Indonesia','Far East / Southeast Asia'],['surabaya','Surabaya','سورابايا','Indonesia','Far East / Southeast Asia'],['singapore','Singapore','سنغافورة','Singapore','Far East / Southeast Asia'],['ho-chi-minh','Ho Chi Minh City','هو تشي منه','Vietnam','Far East / Southeast Asia'],['haiphong','Haiphong','هايفونج','Vietnam','Far East / Southeast Asia'],['busan','Busan','بوسان','South Korea','Far East / Southeast Asia'],['shanghai','Shanghai','شنغهاي','China','Far East / Southeast Asia'],['qingdao','Qingdao','تشينغداو','China','Far East / Southeast Asia'],['shenzhen','Shenzhen','شنتشن','China','Far East / Southeast Asia'],['ningbo','Ningbo','نينغبو','China','Far East / Southeast Asia'],['tianjin','Tianjin','تيانجين','China','Far East / Southeast Asia'],['nansha','Nansha','نانشا','China','Far East / Southeast Asia'],['shekou','Shekou','شيكو','China','Far East / Southeast Asia'],['xiamen','Xiamen','شيامن','China','Far East / Southeast Asia'],['dalian','Dalian','داليان','China','Far East / Southeast Asia']
].map(([id,name,ar,country,region])=>({id,name,ar,country,region,enabled:1}));
export const initialRates=[['aqaba',20,500],['aqaba',40,800],['mundra',20,480],['nhava-sheva',20,480],['jeddah',20,500],['jeddah',40,800],['karachi',20,400],['karachi',40,600]];
export const settingsDefaults={
logo:'/assets/ccm-logo.png',adminLogo:'/assets/ccm-logo.png',phone:'03 4844463',email:'info@ccmshipping.com',address:'21 Amien Fekhry St., Ramal Station, Alexandria, Egypt',addressAr:'٢١ شارع أمين فكري، محطة الرمل، الإسكندرية، مصر',whatsapp:'',linkedin:'https://www.linkedin.com/company/ccm-commander-cargo-maritime/posts/',facebook:'',instagram:'',
hero:'Shipping from Egypt, made simple.',heroAr:'الشحن من مصر، ببساطة.',subheading:'Search shipping rates, book shipments and track your cargo with CCM.',subheadingAr:'ابحث عن أسعار الشحن، واحجز شحنتك، وتابع بضائعك مع CCM.',footer:'Connecting businesses to global markets. Reliable shipping solutions from Sokhna Port, Egypt.',footerAr:'نربط الشركات بالأسواق العالمية من خلال حلول شحن موثوقة من ميناء السخنة، مصر.',
fcl:'A full container for your cargo. Straightforward shipping with 20ft and 40ft options.',fclAr:'حاوية كاملة لبضائعك. شحن مبسط مع خيارات حاويات ٢٠ و٤٠ قدماً.',lcl:'Share container space and ship the volume you need, with rates available on request.',lclAr:'شارك مساحة الحاوية واشحن الكمية التي تحتاجها. الأسعار متاحة عند الطلب.',inland:'Connect your sea freight journey with international inland transportation.',inlandAr:'أكمل رحلة شحنتك البحرية مع خدمات النقل البري الدولي.',
navigation:[{label:'Company',ar:'الشركة',items:[{label:'About CCM',ar:'عن CCM',href:'/about'},{label:'Global Reach',ar:'شبكتنا العالمية',href:'/global-reach'},{label:'Contact Us',ar:'تواصل معنا',href:'/contact'}]},{label:'Solutions',ar:'حلولنا',items:[{label:'FCL Shipping',ar:'شحن الحاويات الكاملة',href:'/fcl-shipping-egypt'},{label:'LCL Shipping',ar:'الشحن الجزئي',href:'/lcl-shipping-egypt'},{label:'Inland Transportation',ar:'النقل البري',href:'/inland-transportation'}]},{label:'Resources',ar:'الموارد',items:[{label:'Blog',ar:'المدونة',href:'/blog'},{label:'Shipping Guides & FAQs',ar:'دليل الشحن والأسئلة الشائعة',href:'/guides'}]}]
};
export const faqs=[
['Where can I ship from?','Shipping rates on this platform currently depart from Sokhna Port, Egypt. Explore the destination selector to see supported ports.','من أين يمكنني الشحن؟','أسعار الشحن المتاحة حالياً على المنصة تنطلق من ميناء السخنة، مصر. اختر وجهتك من قائمة الموانئ المدعومة.'],
['Do I need an account to search rates?','Yes. Sign in or create a free CCM account before searching rates.','هل أحتاج إلى حساب للبحث عن الأسعار؟','نعم، سجّل الدخول أو أنشئ حساب CCM مجاناً قبل البحث عن الأسعار.'],
['When do I need company verification?','You can search rates immediately after registering. To book, upload your Commercial Register and Tax Card for manual review by CCM.','متى أحتاج إلى توثيق الشركة؟','يمكنك البحث عن الأسعار فور التسجيل. للحجز، ارفع السجل التجاري والبطاقة الضريبية لمراجعتها من فريق CCM.'],
['Do 40ft Dry and High Cube have the same price?','Yes. The 40ft selling rate applies to both 40ft Dry and 40ft High Cube containers.','هل سعر حاويات ٤٠ قدماً العادية والمرتفعة واحد؟','نعم، ينطبق سعر ٤٠ قدماً على الحاويات الجافة العادية والمرتفعة.'],
['How is shipment tracking updated?','The CCM team updates shipment milestones manually. The timeline shows the latest recorded status and update time.','كيف يتم تحديث تتبع الشحنة؟','يحدث فريق CCM مراحل الشحن يدوياً. يعرض التتبع آخر حالة مسجلة ووقت تحديثها.'],
['Are displayed rates final?','Rates, schedules and availability are subject to final confirmation and may change due to market or geopolitical conditions.','هل الأسعار المعروضة نهائية؟','تخضع الأسعار والجداول والتوافر للتأكيد النهائي، وقد تتغير بسبب ظروف السوق أو الظروف الجيوسياسية.']
];
