import {env} from 'cloudflare:workers';
import {initialRates,destinations,settingsDefaults} from './data';
export const runtime=()=>env as unknown as {DB:D1Database,BUCKET:R2Bucket,ADMIN_SETUP_TOKEN?:string};
export const db=()=>{const v=runtime().DB;if(!v)throw new Error('Database unavailable');return v};
export const now=()=>new Date().toISOString();
export const uid=()=>crypto.randomUUID();
export async function seed(){if(await db().prepare("SELECT key FROM settings WHERE key='initialized'").first())return;const q=[db().prepare("INSERT OR IGNORE INTO settings(key,value) VALUES('site',?)").bind(JSON.stringify(settingsDefaults)),...destinations.map(p=>db().prepare('INSERT OR IGNORE INTO ports(id,name,ar,country,region,enabled) VALUES(?,?,?,?,?,1)').bind(p.id,p.name,p.ar,p.country,p.region)),...initialRates.map(([dest,size,price])=>db().prepare('INSERT OR IGNORE INTO rates(id,destination,size,price,currency,updated) VALUES(?,?,?,?,?,?)').bind(`${dest}-${size}`,dest,size,price,'USD',now())),db().prepare("INSERT OR IGNORE INTO settings(key,value) VALUES('initialized','1')")];await db().batch(q)}
export async function siteSettings(){const row=await db().prepare("SELECT value FROM settings WHERE key='site'").first<{value:string}>();return {...settingsDefaults,...(row?JSON.parse(row.value):{})}}
export class HttpError extends Error{constructor(public status:number,message:string,public code=''){super(message)}}
export function insist(v:unknown,msg:string,status=400):asserts v{if(!v)throw new HttpError(status,msg)}
export async function sha(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(v=>v.toString(16).padStart(2,'0')).join('')}
export async function hashPassword(password:string,salt?:string){const s=salt||uid()+uid();const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const b=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-512',iterations:100000,salt:new TextEncoder().encode(s)},k,512);return s+':'+Array.from(new Uint8Array(b)).map(x=>x.toString(16).padStart(2,'0')).join('')}
export function constantEqual(a:string,b:string){if(a.length!==b.length)return false;let x=0;for(let i=0;i<a.length;i++)x|=a.charCodeAt(i)^b.charCodeAt(i);return x===0}
export function cookie(req:Request,key:string){return (req.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith(key+'='))?.slice(key.length+1)||''}
export function cookieValue(req:Request,key:string,val:string,seconds:number){const secure=new URL(req.url).protocol==='https:';return `${key}=${val}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${seconds}${secure?'; Secure':''}`}
export async function currentUser(req:Request){const token=cookie(req,'ccm_session');if(!token)return null;return db().prepare('SELECT u.id,u.email,u.name,u.phone,u.role,c.name as company,c.id as company_id,c.volume,c.verification,c.reason FROM sessions s JOIN users u ON u.id=s.user_id LEFT JOIN companies c ON c.user_id=u.id WHERE s.token=? AND s.expires>?').bind(await sha(token),Date.now()).first<any>()}
export async function requireUser(req:Request,admin=false,full=false){const u=await currentUser(req);if(!u)throw new HttpError(401,'Please sign in to continue.','LOGIN_REQUIRED');if(admin&&!['admin','sales'].includes(u.role))throw new HttpError(403,'Administrator access required.');if(full&&u.role!=='admin')throw new HttpError(403,'Only an administrator can make this change.');return u}
export async function session(req:Request,id:string,admin=false){const t=uid()+uid();const seconds=admin?43200:2592000;await db().prepare('INSERT INTO sessions(token,user_id,expires) VALUES(?,?,?)').bind(await sha(t),id,Date.now()+seconds*1000).run();return cookieValue(req,'ccm_session',t,seconds)}
export async function throttle(req:Request,scope:string,limit=20,seconds=900){const ip=req.headers.get('cf-connecting-ip')||'local';const k=scope+':'+await sha(ip);const t=Date.now();const row=await db().prepare('INSERT INTO limits(key,count,reset) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN reset<? THEN 1 ELSE count+1 END,reset=CASE WHEN reset<? THEN ? ELSE reset END RETURNING count').bind(k,t+seconds*1000,t,t,t+seconds*1000).first<{count:number}>();if(row&&row.count>limit)throw new HttpError(429,'Too many attempts. Please try again later.')}
export function sameOrigin(req:Request){const o=req.headers.get('origin');if(o&&o!==new URL(req.url).origin)throw new HttpError(403,'Request origin not allowed.');if(req.headers.get('sec-fetch-site')==='cross-site')throw new HttpError(403,'Cross-site requests are not allowed.')}
export const clean=(v:unknown,max=500)=>String(v??'').trim().slice(0,max);
export const emailOk=(s:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(s);
export const safeHref=(s:string)=>s.startsWith('/')&&!s.startsWith('//')||/^https:\/\//i.test(s)||/^mailto:|^tel:/i.test(s);
export async function availableRate(dest:string,size:number,date:string){return db().prepare("SELECT * FROM rates WHERE destination=? AND size=? AND enabled=1 AND (valid_until IS NULL OR valid_until='' OR valid_until>=?)").bind(dest,size,date).first<any>()}

export function validDate(v:unknown){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const d=new Date(v+'T00:00:00Z');return !Number.isNaN(d.getTime())&&d.toISOString().slice(0,10)===v}
