import PublicSite from '@/components/ccm/PublicSite';
import Dashboard from '@/components/ccm/Dashboard';
import {notFound} from 'next/navigation';
import {cookies} from 'next/headers';
import {destinations} from '@/lib/data';
import {db,seed} from '@/lib/server';
export const dynamic='force-dynamic';
const routes:Record<string,[string,string]>={'about':['about','About CCM'],'global-reach':['global-reach','Global reach'],'contact':['contact','Contact CCM'],'rates':['rates','Container shipping rates from Egypt'],'track':['track','Track your shipment'],'fcl-shipping-egypt':['fcl','FCL shipping Egypt'],'lcl-shipping-egypt':['lcl','LCL shipping Egypt'],'inland-transportation':['inland','International inland transportation'],'guides':['guides','Shipping guides and FAQs'],'blog':['blog','Shipping blog'],'privacy':['privacy','Privacy and terms'],'login':['login','Sign in'],'register':['register','Create account'],'admin/login':['admin-login','CCM admin sign in'],'admin/setup':['admin-setup','CCM admin setup'],'shipping-from-sokhna-port':['rates','Shipping from Sokhna Port']};
export async function generateMetadata({params}:any){const {slug}=await params;const p=slug.join('/');let title=routes[p]?.[1]||'CCM';if(p.startsWith('shipping-egypt-to-'))title='Shipping from Egypt to '+(destinations.find(d=>d.id===p.replace('shipping-egypt-to-',''))?.name||'global destinations');if(p.startsWith('blog/'))try{await seed();title=(await db().prepare('SELECT title FROM articles WHERE slug=? AND published=1').bind(slug[1]).first<any>())?.title||'Article'}catch{}return {title,description:`${title}. CCM Shipping Agency connects businesses with global markets from Sokhna Port, Egypt.`,alternates:{canonical:'/'+p},robots:/^(admin|dashboard|login|register)/.test(p)?{index:false,follow:false}:undefined}}
export default async function Page({params}:any){const {slug}=await params;const p=slug.join('/');if((slug[0]==='admin'&&!['login','setup'].includes(slug[1]))||slug[0]==='dashboard')return <Dashboard admin={slug[0]==='admin'} section={slug[1]||'overview'} lang={(await cookies()).get('ccm_lang')?.value||'en'}/>;if(routes[p])return <PublicSite page={routes[p][0]}/>;if(slug[0]==='blog'&&slug[1])return <PublicSite page="article" slug={slug[1]}/>;if(p.startsWith('shipping-egypt-to-')&&['jeddah','jebel-ali'].includes(p.replace('shipping-egypt-to-','')))return <PublicSite page="destination" slug={p.replace('shipping-egypt-to-','')}/>;notFound()}
